### ISSUE TITLE
No dockerfile here?

### ISSUE THREAD

**Issue by rogersachan** [matrix-org/matrix-synapse-docker#1]

**Comment by turt2live** [comment]
As I understand it, this repo was created as part of the conversation at https://github.com/matrix-org/synapse/pull/2846

The specific comment thread of interest is: https://github.com/matrix-org/synapse/pull/2846#issuecomment-383124282

**Comment by michaelkaye** [comment]
Ah yes, thanks for the reminder - i'll close this issue and remove the repository.
